spring:
  application:
    name: open-chat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/open_chat
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

aws:
  access-key: AKIAXYKJRLFYOGZSQSGZ
  secret-key: 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
  region: us-east-2
  attachments-bucket: open-chat-attachments
  cognito:
    user-pool-id: us-east-2_cQqrqGoe5
    app-client-id: 661d1ashh62bvj8m9g4r2699qm
    app-client-secret: 1o94g0mtth93frsihfuocl79918muchdc5iaikjcohokbvk8uc03

jwks:
  url: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_cQqrqGoe5/.well-known/jwks.json

openai:
  model: gpt-3.5-turbo-0301
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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

gemini:
  api:
    key: AIzaSyDWkne0n1KzsTZWEzp3x7SaHyafjd0ueHU
    url: https://generativelanguage.googleapis.com/v1beta/models

# STATE
state:
  base-url: ${OPEN_STATE_URL:http://localhost:8545/api}

# FIREBASE
app:
  firebase-configuration-file: open-chat-5f7ba-firebase-adminsdk-1523p-0a596434ea.json