spring:
  application:
    name: open-chat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/open_chat
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

aws:
  access-key: AKIAUSWCDIFRDTGV52OL
  secret-key: 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
  region: us-west-2
  cognito:
    user-pool-id: us-west-2_aIKYDnG0g
    app-client-id: lbl41afhrnidb37k8gjph6smv
    app-client-secret: g2ur12s1gh2723f6t6gp5q4t88cu54d6qolkpa0vhps5pf7b65
