spring:
  application:
    name: open-chat
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3310/open_chat?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: ${spring.datasource.hikari.maximum-pool-size}
  jpa:
    hibernate:
      ddl-auto: none

aws:
  access-key:
  secret-key:
  region: us-west-2
  cognito:
    user-pool-id:
    app-client-id:
    app-client-secret:
