spring:
  application:
    name: open-chat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/open_chat
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gcp:
      credentials:
        location: file:/Users/beksultan/Documents/open-messanger/alien-scope-428812-i2-0794e36fcbee.json
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-2
  attachments-bucket: ${AWS_ATTACHMENTS_BUCKET}
  recordings-bucket: ${AWS_RECORDINGS_BUCKET}
  transcripts-bucket: ${AWS_TRANSCRIPTS_BUCKET}
  cognito:
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID}
    app-client-secret: ${AWS_COGNITO_APP_CLIENT_SECRET}

jwks:
  url: ${AWS_COGNITO_JWKS_URL}

openai:
  model: ${OPENAI_MODEL}
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}


system:
  GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}

kms:
  url: ws://127.0.0.1:8888/kurento

server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: kurento
    key-store-type: JKS
    key-alias: kurento-selfsigned
  port: 8443


# STATE
state:
  base-url: ${OPEN_STATE_URL:http://localhost:8545/api}

# FIREBASE
app:
  firebase-configuration-file: ${FIREBASE_CONFIG_FILE}