spring:
  application:
    name: open-chat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/open_chat
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

aws:
  access-key: AKIAXYKJRLFYPXI732OX
  secret-key: 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
  region: us-east-2
  cognito:
    user-pool-id: us-east-2_cQqrqGoe5
    app-client-id: 661d1ashh62bvj8m9g4r2699qm
    app-client-secret: 1o94g0mtth93frsihfuocl79918muchdc5iaikjcohokbvk8uc03

jwks:
  url: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_cQqrqGoe5/.well-known/jwks.json
