name: Build

on:
  push: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
      - name: Gradle build
        run: ./gradlew clean build --parallel